language: python
python:
  - "2.7"
  - "3.5.1"

sudo: required
install: "pip install -r requirements.txt"
script:
  - nosetests  --with-coverage --cover-erase --cover-package=josh --nologcapture

after_success:
  - coveralls